add a bunch of ports from legacy upstream

diff --git a/ports/build b/ports/build
--- a/ports/build
+++ b/ports/build
@@ -250,12 +250,31 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
     source "${PACKAGE_DIR}/../ports.info"
     PACKAGE_INFO_TMP="${PACKAGE_DIR}/package.info.tmp"
 
+    if [[ -z "${PKG_DOWNLOAD_NAME}" ]]; then
+      PKG_DOWNLOAD_NAME="${PKG_NAME}"
+    fi
     echo "Legacy Portmaster Build - Getting info from legacy URLS"
 
-    PKG_GIT_SHA=$(curl -L "https://api.github.com/repos/${LEGACY_PORTMASTER_ORG}/${LEGACY_PORTMASTER_REPO}/contents?sha=${LEGACY_PORTMASTER_BRANCH}&path=/&page=1&per_page=1" -q 2> /dev/null | grep "${PKG_NAME}.zip" -A 2 | grep -i sha | head -1 | sed -E 's|.*: "(.*)",|\1|g')
-    PKG_VERSION=$(wget -O- "https://api.github.com/repos/${LEGACY_PORTMASTER_ORG}/${LEGACY_PORTMASTER_REPO}/commits?sha=${LEGACY_PORTMASTER_BRANCH}&path=${PKG_NAME}.zip&page=1&per_page=1" -q 2> /dev/null | grep -i sha | head -1 | sed -E 's|.*: "(.*)",|\1|g')
+    GITHUB_AUTH=""
+    if [[ -n "${GITHUB_TOKEN}" ]]; then
+      GITHUB_AUTH="Authorization: token ${GITHUB_TOKEN}"
+    fi
+    GITHUB_SHA_URL="https://api.github.com/repos/${LEGACY_PORTMASTER_ORG}/${LEGACY_PORTMASTER_REPO}/contents?sha=${LEGACY_PORTMASTER_BRANCH}&path=/&page=1&per_page=1"
+    PKG_VERSION_URL="https://api.github.com/repos/${LEGACY_PORTMASTER_ORG}/${LEGACY_PORTMASTER_REPO}/commits?sha=${LEGACY_PORTMASTER_BRANCH}&path=${PKG_DOWNLOAD_NAME}.zip&page=1&per_page=1"
+    echo "Github SHA URL: ${GITHUB_SHA_URL}"
+    PKG_GIT_SHA=$(curl -H "${GITHUB_AUTH}" -L "${GITHUB_SHA_URL}" -q 2> /dev/null | grep -i "${PKG_DOWNLOAD_NAME}.zip" -A 3 | grep -i "\"sha\"" | head -1 | sed -E 's|.*: "(.*)",|\1|g')
+    if [[ -z "${PKG_GIT_SHA}" ]]; then
+      echo "Could not find ${PKG_NAME}.zip in ${GITHUB_SHA_URL}"
+      exit 1
+    fi
+    echo "Package Version URL: ${PKG_VERSION_URL}"
 
-    PKG_URL="https://github.com/${LEGACY_PORTMASTER_ORG}/${LEGACY_PORTMASTER_REPO}/raw/${PKG_VERSION}/${PKG_NAME}.zip"
+    PKG_VERSION=$(wget --header="$GITHUB_AUTH" -O- "${PKG_VERSION_URL}" -q 2> /dev/null | grep -i sha | head -1 | sed -E 's|.*: "(.*)",|\1|g')
+    if [[ -z "${PKG_VERSION}" ]]; then
+      echo "Could not find a sha in: ${GITHUB_SHA_URL}"
+      exit 1
+    fi
+    PKG_URL="https://github.com/${LEGACY_PORTMASTER_ORG}/${LEGACY_PORTMASTER_REPO}/raw/${PKG_VERSION}/${PKG_DOWNLOAD_NAME}.zip"
     GET_HANDLER_SUPPORT="archive"
     echo "PKG_GIT_SHA: ${PKG_GIT_SHA} PKG_VERSION: ${PKG_VERSION} PKG_URL: ${PKG_URL}"
 
